### ISSUE TITLE
Wrong calulation of kWh

### ISSUE THREAD

**Issue by Allram** [balmli/com.tesla.charger#1]
Thanks for the app, works great in Homey! :)

But the calculation for kWh is not correct. Does it calculate the kW and multiply it by the time the car is charging?
I have dynamic charging system both at home and at my workplace. I can charge up to 16.5kW, but usually i charge in the area of ~5-10kW depending on other cars connected.
When the car is done, i get a notification about how much the car has charged, and it says the car has charged 206.43kWh today, i only have a model S75D, so that should be quite impossible :)

**Comment by balmli** [comment]
Thanks for the interest !

I will have a look at it.

**Comment by balmli** [comment]
Found one bug when checking the difference in time between the first and second meter power calculation. 

You can call the "Reset power meter" action to when you start charging, and see if the value in the Charging stopped - trigger (meter_power) is the same as the totalt meter power value.

Pull v. 1.0.28 ... and test  :-)

**Comment by Allram** [comment]
Worked like a charm! Pulled 1.0.28 abd did a "Reset Power meter" when i started charging, and now it shows the correct kWh :)
