### ISSUE TITLE
Battery ranges

### ISSUE THREAD

**Issue by Allram** [balmli/com.tesla.charger#10]
Hello,

Today we can choose between:
Estimated battery Range (lower than the car assumes)
Ideal battery Range (you'r most likely not goind to get to this range)

But i would like a third option:
Typical battery range, is this is what the car itself show in the dashboard.

Teslamate - https://github.com/adriankumpf/teslamate
Pulls it from the Tesla API with this: 'est_battery_range'

**Comment by balmli** [comment]
Hi,

Right now the current values for battery is in use:

- battery_range
- est_batery_range

The third value: ideal_battery_range is not used.

In settings you can choose from:

- Ideal -> battery_range
- Estimated -> est_batery_range

I will change this to:

- Standard -> battery_range
- Estimated -> est_batery_range
- Ideal -> ideal_battery_range

**Comment by balmli** [comment]
Please test v. 1.3.0:

https://homey.app/a/com.tesla.charger/test/

**Comment by balmli** [comment]
Tested ?

**Comment by Allram** [comment]
Yes, sorry.

Works great with the new battery-range selector 😀
