### ISSUE TITLE
Change between battery range calculations

### ISSUE THREAD

**Issue by Allram** [balmli/com.tesla.charger#2]
Hello,

Is it possible to add a switch in advanced settings to set it to different battery range settings? As of now it shows 432km for my car (S75D), i guess that's the 'ideal' settings, but I would like to have it to show the 'typical' which is a more "safe" drive range.

**Comment by balmli** [comment]
Yes, will have a look at it.

**Comment by balmli** [comment]
Check v. 1.0.32.

And please test :-)

**Comment by balmli** [comment]
A couple of fixes, so now you can look for 1.0.34.

**Comment by Allram** [comment]
Works great, thanks!
