### ISSUE TITLE
‘Is Home’ is failing if true.

### ISSUE THREAD

**Issue by Genghes** [balmli/com.tesla.charger#4]
If 'Is Home' is true, the next flow card will fail as a property is undefined.

See attached screenshot.

![image](https://user-images.githubusercontent.com/10722186/99909436-ce4b2c80-2ce8-11eb-935c-8c368714c3db.jpeg)

**Comment by Genghes** [comment]
The error seems to be on the flow card checking for update, but regardless which card is after the 'Is Home' it fails if 'Is Home' is true.
So if 'Is Home' is true there is something at the end of that code not being able to clean up something?

The error message also indicates this.

**Comment by balmli** [comment]
Thank you for reporting!

Should be fixed in v. 1.0.35.

**Comment by Genghes** [comment]
Jepp.. Works fine in .35
