### ISSUE TITLE
Vehicle come home trigger does not work?

### ISSUE THREAD

**Issue by MbenzNo** [balmli/com.tesla.charger#5]
Made a short test flow for when the car comes home. It newer triggers.  Am I doing it wrong?
Testing the flows sends me a notification.
https://homey.app/f/efmswo

**Comment by balmli** [comment]
Hi,

In Advanced settings, you can change the "Data fetch interval (minutes)".  The default is 60 minutes, and the minimum is 1 minute.  You can also change the interval by the "Set 'Data fetch interval'" - flow.

If the home trigger is going to be successful you need:

- the position of the home needs to be within the "Location accuracy (meters)", which also can be changed from Adv. settings. That's the length in meters from the position of the Homey.

- the Data fetch interval should be a small number.  If it is 60 minutes, it will take long for the app to see the change and report that the "Vehicle came home" .

So try changing to 1 minute, and check that the position of the Homey is set correctly in the Homey mobile app.

**Comment by balmli** [comment]
More info about the app here:

https://community.athom.com/t/tesla-smart-charger/30648

**Comment by MbenzNo** [comment]
Thank You. Will continue any discussions in community,
