### ISSUE TITLE
Cannot login to the app, credentials are right though...

### ISSUE THREAD

**Issue by DSGuess** [balmli/com.tesla.charger#6]
I wanted to try your app on my homey. Unfortunately it does not let me login tot my tesla account. I haven't got a clue how to login at the moment. Do you have a tip for me?

Thank you in advance!

**Comment by MbenzNo** [comment]
Tesla has pulled the plug on the old authentication method. It seems that the car no longer updates data to the app.

**Comment by balmli** [comment]
I have updated to the new authentication system for Tesla.

Look for v. 1.0.37 or newer in the Homey Community Store:

https://store.homey.community/app/com.tesla.charger

**Comment by DSGuess** [comment]
Thanks! I will install it as soon as it is available on the app store and report back to you!

**Comment by Genghes** [comment]
Upgraded from 1.1.3 to 1.2.6 and now device is unavailable and reapir does not work. It accepts my credentials bot device still unavailable and says it needs to be repaired.

Any tips or do I have to remove and add device.
I really dont want to do that as i have a ton of flows..

**Comment by balmli** [comment]
OK, I think you found a bug..  

I will fix, and hope you can test, and you won't have to remove + add the device and recreate flows.   

Will update when the test-version is ready.

**Comment by balmli** [comment]
V. 1.2.7 with a fix for repairing.  Please test :-) 

https://homey.app/a/com.tesla.charger/test/

**Comment by Genghes** [comment]
Installed 1.2.8 and it worked perfectly.. 
Thank you.

**Comment by Genghes** [comment]
Spoke too soon it seems..
The app is unable to get data from the car.
If I restart the app it again needs to be repaired.
Repais seems to succseed, but the data about the car is days old and does not refresh.
(v1.2.8)

**Comment by balmli** [comment]
Hi @Genghes 

Yes, I will have a look at it again

**Comment by balmli** [comment]
@Genghes 

Check v. 1.2.9 for a fix.
https://homey.app/a/com.tesla.charger/test/

**Comment by Genghes** [comment]
Looks like it works. Got status from most sensors. I guess the rest will update once the car starts moving or charging..
