### ISSUE TITLE
Adding new car (Model 3) fails

### ISSUE THREAD

**Issue by kriborg** [balmli/com.tesla.charger#7]
Hi !

I have just installed your app , the old Tesla app has been removed from GitHub (https://github.com/irritanterik/homey-tesla.com)

The problem is adding my Tesla, after successful login, still no tesla device in my device overview ? I can see that the screen "choose your device" is showing for 2 seconds in the background before i'm sent back to the device overview.

Same result in http://developer.athom.com/tools/pair

I have tried rebooting my Homey.

Running Homey version 4.2.0

**Comment by ezwep** [comment]
It doesn't work for me either. I have a model 3 and am using version 5.0.0-rc64

**Comment by balmli** [comment]
Thanks for reporting.  Yes, I tested via http://developer.athom.com/tools/pair and expected that the mobile app pairing works the same way.

I will create a fix today that I hope you can test.

**Comment by kriborg** [comment]
Så klart :) ofcourse

**Comment by balmli** [comment]
Please test, v. 1.1.2:

https://homey.app/a/com.tesla.charger/test/

**Comment by kriborg** [comment]
V1.1.2 is working like it should 👍👍

**Comment by balmli** [comment]
Thanks!  Fixed another bug, and 1.1.3 is actually official now.
