### ISSUE TITLE
CHARGING_STATE_DISCONNECTED is not defined

### ISSUE THREAD

**Issue by yhaugom** [balmli/com.tesla.charger#9]
Fails on condition card "Is plugged in" with error message "CHARGING_STATE_DISCONNECTED is not defined".
![Fil_000](https://user-images.githubusercontent.com/1016457/109786934-fd3d3c80-7c0d-11eb-8e12-6ee638b83915.jpeg)

**Comment by balmli** [comment]
Thank you for reporting !

Check v. 1.2.6 for a fix:

https://homey.app/a/com.tesla.charger/test/

**Comment by yhaugom** [comment]
Works in 1.2.6. Thank you for fixing fast! 👍🏼😊

Med vennlig hilsen
Yngve Bøe Haugom
Mobil: +47 996 96 088
________________________________
Fra: Bjørnar Almli <notifications@github.com>
Sendt: Thursday, March 4, 2021 7:41:52 AM
Til: balmli/com.tesla.charger <com.tesla.charger@noreply.github.com>
Kopi: Yngve Haugom <yngve_haugom@hotmail.com>; Author <author@noreply.github.com>
Emne: Re: [balmli/com.tesla.charger] CHARGING_STATE_DISCONNECTED is not defined (#9)


Closed #9<https://github.com/balmli/com.tesla.charger/issues/9>.
